# Form implementation generated from reading ui file 'hashui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
 
from seperatehash import call_sha224,call_sha256, call_sha384, call_sha512, call_sha3_224, call_sha3_256, call_sha3_384, call_sha3_512, call_shake128, call_shake256

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 817)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.hashfuclb = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hashfuclb.setFont(font)
        self.hashfuclb.setObjectName("hashfuclb")
        self.gridLayout.addWidget(self.hashfuclb, 0, 0, 1, 2)
        self.sha224button = QtWidgets.QRadioButton(parent=self.widget)
        self.sha224button.setObjectName("sha224button")
        self.gridLayout.addWidget(self.sha224button, 1, 0, 1, 1)
        self.sha256button = QtWidgets.QRadioButton(parent=self.widget)
        self.sha256button.setObjectName("sha256button")
        self.gridLayout.addWidget(self.sha256button, 1, 1, 1, 1)
        self.sha384button = QtWidgets.QRadioButton(parent=self.widget)
        self.sha384button.setObjectName("sha384button")
        self.gridLayout.addWidget(self.sha384button, 1, 2, 1, 1)
        self.sha512button = QtWidgets.QRadioButton(parent=self.widget)
        self.sha512button.setObjectName("sha512button")
        self.gridLayout.addWidget(self.sha512button, 1, 3, 1, 1)
        self.sha3_224button = QtWidgets.QRadioButton(parent=self.widget)
        self.sha3_224button.setObjectName("sha3_224button")
        self.gridLayout.addWidget(self.sha3_224button, 1, 4, 1, 1)
        self.sha3_256button = QtWidgets.QRadioButton(parent=self.widget)
        self.sha3_256button.setObjectName("sha3_256button")
        self.gridLayout.addWidget(self.sha3_256button, 1, 5, 1, 1)
        self.sha3_384button = QtWidgets.QRadioButton(parent=self.widget)
        self.sha3_384button.setObjectName("sha3_384button")
        self.gridLayout.addWidget(self.sha3_384button, 1, 6, 1, 1)
        self.sha3_512button = QtWidgets.QRadioButton(parent=self.widget)
        self.sha3_512button.setObjectName("sha3_512button")
        self.gridLayout.addWidget(self.sha3_512button, 1, 7, 1, 1)
        self.shake128button = QtWidgets.QRadioButton(parent=self.widget)
        self.shake128button.setObjectName("shake128button")
        self.gridLayout.addWidget(self.shake128button, 1, 8, 1, 1)
        self.shake256button = QtWidgets.QRadioButton(parent=self.widget)
        self.shake256button.setObjectName("shake256button")
        self.gridLayout.addWidget(self.shake256button, 1, 9, 1, 1)
        self.buttongroup = QtWidgets.QButtonGroup()
        self.buttongroup.addButton(self.sha224button)
        self.buttongroup.addButton(self.sha256button)
        self.buttongroup.addButton(self.sha384button)
        self.buttongroup.addButton(self.sha512button)
        self.buttongroup.addButton(self.sha3_224button)
        self.buttongroup.addButton(self.sha3_384button)
        self.buttongroup.addButton(self.sha3_256button)
        self.buttongroup.addButton(self.sha3_512button)
        self.buttongroup.addButton(self.shake128button)
        self.buttongroup.addButton(self.shake256button)
        self.outputlengthlb = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.outputlengthlb.setFont(font)
        self.outputlengthlb.setObjectName("outputlengthlb")
        self.gridLayout.addWidget(self.outputlengthlb, 2, 0, 1, 4)
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 3, 0, 1, 9)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inptexlb = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inptexlb.setFont(font)
        self.inptexlb.setObjectName("inptexlb")
        self.verticalLayout.addWidget(self.inptexlb)
        self.inptextle = QtWidgets.QTextEdit(parent=self.widget_2)
        self.inptextle.setObjectName("inptextle")
        self.verticalLayout.addWidget(self.inptextle)
        self.inpfilelb = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inpfilelb.setFont(font)
        self.inpfilelb.setObjectName("inpfilelb")
        self.verticalLayout.addWidget(self.inpfilelb)
        self.inpfilele = QtWidgets.QTextEdit(parent=self.widget_2)
        self.inpfilele.setObjectName("inpfilele")
        self.verticalLayout.addWidget(self.inpfilele)
        self.outputlb = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.outputlb.setFont(font)
        self.outputlb.setObjectName("outputlb")
        self.verticalLayout.addWidget(self.outputlb)
        self.outputle = QtWidgets.QTextEdit(parent=self.widget_2)
        self.outputle.setObjectName("outputle")
        self.verticalLayout.addWidget(self.outputle)
        self.resultlb = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resultlb.setFont(font)
        self.resultlb.setObjectName("resultlb")
        self.verticalLayout.addWidget(self.resultlb)
        self.resultle = QtWidgets.QTextEdit(parent=self.widget_2)
        self.resultle.setObjectName("resultle")
        self.verticalLayout.addWidget(self.resultle)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.hashbutton = QtWidgets.QPushButton(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hashbutton.setFont(font)
        self.hashbutton.setObjectName("hashbutton")
        self.hashbutton.clicked.connect(self.HashClicked)
        self.horizontalLayout.addWidget(self.hashbutton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hash a text"))
        self.hashfuclb.setText(_translate("MainWindow", "Hash Functions"))
        self.sha224button.setText(_translate("MainWindow", "SHA224"))
        self.sha256button.setText(_translate("MainWindow", "SHA256"))
        self.sha384button.setText(_translate("MainWindow", "SHA384"))
        self.sha512button.setText(_translate("MainWindow", "SHA512"))
        self.sha3_224button.setText(_translate("MainWindow", "SHA3-224"))
        self.sha3_256button.setText(_translate("MainWindow", "SHA3-256"))
        self.sha3_384button.setText(_translate("MainWindow", "SHA3-384"))
        self.sha3_512button.setText(_translate("MainWindow", "SHA3-512"))
        self.shake128button.setText(_translate("MainWindow", "SHAKE128"))
        self.shake256button.setText(_translate("MainWindow", "SHAKE256"))
        self.outputlengthlb.setText(_translate("MainWindow", "Output length d ( for SHAKE )"))
        self.inptexlb.setText(_translate("MainWindow", "Input text"))
        self.inpfilelb.setText(_translate("MainWindow", "Input file"))
        self.outputlb.setText(_translate("MainWindow", "Output file"))
        self.resultlb.setText(_translate("MainWindow", "Reuslt"))
        self.hashbutton.setText(_translate("MainWindow", "Hash!"))
    def HashClicked(self):
        selected_button = self.buttongroup.checkedButton()
        algo = selected_button.text().strip()
        digestlength = self.textEdit.toPlainText().strip()
        input = self.inptextle.toPlainText().strip()
        inputfile = self.inpfilele.toPlainText().strip()
        outputfile = self.outputle.toPlainText().strip()
        if (algo == "SHA224"):
            res = call_sha224(input, inputfile, outputfile)
            if(outputfile != "0"):
                self.resultle.setText(res.decode('utf-8')+ " saved to output file")
            else:
                self.resultle.setText(res.decode('utf-8'))
        if (algo == "SHA256"):
            res = call_sha256(input, inputfile, outputfile)
            if(outputfile != "0"):
                self.resultle.setText(res.decode('utf-8')+ " saved to output file")
            else:
                self.resultle.setText(res.decode('utf-8'))
        if (algo == "SHA384"):
            res = call_sha384(input, inputfile, outputfile)
            if(outputfile != "0"):
                self.resultle.setText(res.decode('utf-8')+ " saved to output file")
            else:
                self.resultle.setText(res.decode('utf-8'))
        if (algo == "SHA512"):
            res = call_sha512(input, inputfile, outputfile)
            if(outputfile != "0"):
                self.resultle.setText(res.decode('utf-8')+ " saved to output file")
            else:
                self.resultle.setText(res.decode('utf-8'))
        if (algo == "SHA3-224"):
            res = call_sha3_224(input, inputfile, outputfile)
            if(outputfile != "0"):
                self.resultle.setText(res.decode('utf-8')+ " saved to output file")
            else:
                self.resultle.setText(res.decode('utf-8'))
        if (algo == "SHA3-256"):
            res = call_sha3_256(input, inputfile, outputfile)
            if(outputfile != "0"):
                self.resultle.setText(res.decode('utf-8')+ " saved to output file")
            else:
                self.resultle.setText(res.decode('utf-8'))
        if (algo == "SHA3-384"):
            res = call_sha3_384(input, inputfile, outputfile)
            if(outputfile != "0"):
                self.resultle.setText(res.decode('utf-8')+ " saved to output file")
            else:
                self.resultle.setText(res.decode('utf-8'))
        if(algo== "SHA3-512"):
            res = call_sha3_512(input, inputfile, outputfile)
            if(outputfile != "0"):
                self.resultle.setText(res.decode('utf-8')+ " saved to output file")
            else:
                self.resultle.setText(res.decode('utf-8'))
        if (algo == "SHAKE128"):
            res = call_shake128(input, inputfile, outputfile, digestlength)
            if(outputfile != "0"):
                self.resultle.setText(res.decode('utf-8')+ " saved to output file")
            else:
                self.resultle.setText(res.decode('utf-8'))
        if (algo == "SHAKE256"):
            res = call_shake256(input, inputfile, outputfile, digestlength)
            if(outputfile != "0"):
                self.resultle.setText(res.decode('utf-8')+ " saved to output file")
            else:
                self.resultle.setText(res.decode('utf-8'))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
